/**
 * Deterministic, evidence-based test/generated-file classification. Never
 * guesses from content semantics — only filename/path patterns and explicit
 * generated-file markers, per the "never fabricate evidence" rule
 * (docs/ARCHITECTURE.md §6).
 */

const TEST_PATH_SEGMENT_PATTERN = /(^|\/)(test|tests|__tests__|spec)(\/|$)/i;
const TEST_FILENAME_PATTERN = /\.(test|spec)\.[a-z0-9]+$/i;
const JAVA_TEST_FILENAME_PATTERN = /(Test|Tests|IT)\.java$/;

export function isTestFile(relPath: string): boolean {
  if (TEST_FILENAME_PATTERN.test(relPath)) return true;
  if (JAVA_TEST_FILENAME_PATTERN.test(relPath)) return true;
  if (TEST_PATH_SEGMENT_PATTERN.test(relPath)) return true;
  return false;
}

const GENERATED_FILENAME_PATTERN = /\.(generated|gen|min|d)\.[a-z0-9]+$/i;
const GENERATED_CONTENT_MARKERS = [
  "@generated",
  "This file was automatically generated",
  "DO NOT EDIT",
  "Code generated by",
];

export function isGeneratedFile(relPath: string, headerText: string | null): boolean {
  if (GENERATED_FILENAME_PATTERN.test(relPath)) return true;
  if (headerText) {
    const sample = headerText.slice(0, 500);
    return GENERATED_CONTENT_MARKERS.some((marker) => sample.includes(marker));
  }
  return false;
}
